/**
 * Sanitize text generated by the LLM before posting back to Slack.
 *
 * Wraps any broadcast mentions (`<!channel>`, `<!subteam^...>`) and user
 * mentions (`<@U...>`) in code spans so the bot can't be used to spam everyone.
 */
const BROADCAST_MENTION_RE = /<!(channel|here|everyone)>/g;
const USER_GROUP_MENTION_RE = /<!subteam\^[^>]+>/g;
const USER_MENTION_RE = /<@[UW][A-Z0-9]+>/g;

export function sanitizeGeneratedSlackMrkdwn(text: string): string {
  return text
    .replace(BROADCAST_MENTION_RE, '`$&`')
    .replace(USER_GROUP_MENTION_RE, '`$&`')
    .replace(USER_MENTION_RE, '`$&`');
}
