[target.aarch64-unknown-linux-gnu]
linker = "zig cc -target aarch64-linux-gnu"

[target.x86_64-unknown-linux-gnu]
linker = "zig cc -target x86_64-linux-gnu -mno-outline-atomics -static-libgcc"
rustflags = ["-C", "target-feature=-crt-static", "-C", "link-arg=-lgcc"]

[build]
rustflags = ["-Z", "avoid-cfgs=rustc_attrs"]
