# [target.aarch64-unknown-linux-gnu]
# linker = "zig cc -target aarch64-linux-gnu"

# Use MUSL target for static linking on x86_64 Linux (Lambda default)
[target.x86_64-unknown-linux-musl]
# Typically, no special linker needed for musl

# Default target (used in Docker build with official base image)
# [target.x86_64-unknown-linux-gnu]
# Use default linker provided by the base image (gcc)
# linker = "zig cc -target x86_64-linux-gnu -mno-outline-atomics -static-libgcc"
# rustflags = ["-C", "target-feature=-crt-static", "-C", "link-arg=-lgcc"]

# Remove build flags requiring nightly
# [build]
# rustflags = ["-Z", "avoid-cfgs=rustc_attrs"]
